// Maps common abbreviations and everyday terms people actually type to the
// canonical type names already used throughout the app (in TYPES_RAW /
// TYPE_GROUPS). This is what lets someone type "GBM" or "brain tumor" and
// land on "Glioblastoma" / "Brain" — the canonical list itself stays exactly
// as-is; this is purely a search-matching layer on top of it.

export const CANCER_TYPE_ALIASES = {
  // Acronyms
  gbm: "Glioblastoma",
  nsclc: "Lung",
  sclc: "Lung",
  tnbc: "Breast",
  her2: "Breast",
  dcis: "Breast",
  cll: "Chronic Lymphocytic Leukemia (CLL)",
  aml: "Acute Myeloid Leukemia (AML)",
  all: "Acute Lymphoblastic Leukemia (ALL)",
  cml: "Chronic Myeloid Leukemia (CML)",
  dlbcl: "Diffuse Large B-Cell Lymphoma (DLBCL)",
  mds: "Myelodysplastic Syndromes (MDS)",
  mpn: "Myeloproliferative Neoplasms (MPN)",
  gist: "Gastrointestinal stromal tumor (GIST)",
  net: "Neuroendocrine tumor (NET)",
  pnet: "Neuroendocrine tumor (NET)",
  cup: "Cancer of Unknown Primary (CUP)",
  lch: "Langerhans Cell Histiocytosis",
  mf: "Mycosis Fungoides / Cutaneous T-Cell Lymphoma",
  ctcl: "Mycosis Fungoides / Cutaneous T-Cell Lymphoma",
  gtd: "Gestational Trophoblastic Disease (GTD)",
  rcc: "Kidney",
  hcc: "Liver",
  acc: "Adrenocortical Carcinoma",
  bcc: "Basal Cell Carcinoma",
  scc: "Squamous Cell Carcinoma",
  cscc: "Cutaneous Squamous Cell Carcinoma",
  wm: "Waldenström Macroglobulinemia",
  et: "Essential Thrombocythemia",
  pv: "Polycythemia Vera",
  pmf: "Primary Myelofibrosis",
  mcl: "Mantle Cell Lymphoma",

  // Everyday terms / plain-language phrasing
  "brain tumor": "Brain",
  "brain cancer": "Brain",
  "lung cancer": "Lung",
  "breast cancer": "Breast",
  "blood cancer": "Blood (leukemia)",
  "bone marrow cancer": "Blood (leukemia)",
  "skin cancer": "Melanoma / skin",
  "stomach cancer": "Gastric / esophageal",
  "esophageal cancer": "Gastric / esophageal",
  "throat cancer": "Head & neck",
  "eye cancer": "Eye (Ocular) Cancer",
  "uterine cancer": "Uterine",
  "womb cancer": "Uterine",
  "kidney cancer": "Kidney",
  "liver cancer": "Liver",
  "colon cancer": "Colorectal",
  "bowel cancer": "Colorectal",
  "rectal cancer": "Colorectal",
  "bone cancer": "Bone Cancer",
  "eye melanoma": "Uveal Melanoma",
  "childhood cancer": "Pediatric",
  "pediatric brain tumor": "Brain",
};