export const TYPES_RAW = [
  "All / general", "Brain", "Lung", "Breast", "Colorectal", "Prostate", "Blood (leukemia)",
  "Lymphoma", "Myeloma", "Ovarian / gynecologic", "Pancreatic", "Melanoma / skin", "Kidney",
  "Bladder", "Head & neck", "Sarcoma", "Liver", "Gastric / esophageal", "Pediatric", "Thyroid", "Cervical", "Testicular", "Oral", "Uterine", "Vulvar", "Penile", "Adrenal", "Small intestine", "Bile duct", "Gallbladder", "Appendix", "Mesothelioma", "Neuroendocrine tumor (NET)", "Gastrointestinal stromal tumor (GIST)", "Other / rare", "Acute Myeloid Leukemia (AML)","Acute Lymphoblastic Leukemia (ALL)","Chronic Myeloid Leukemia (CML)","Chronic Lymphocytic Leukemia (CLL)",
  "Hodgkin Lymphoma","Non-Hodgkin Lymphoma","Follicular Lymphoma","Mantle Cell Lymphoma","Diffuse Large B-Cell Lymphoma (DLBCL)","Burkitt Lymphoma",
  "Waldenström Macroglobulinemia","Myelodysplastic Syndromes (MDS)","Myeloproliferative Neoplasms (MPN)","Essential Thrombocythemia","Polycythemia Vera","Primary Myelofibrosis","Plasma Cell Disorders",
  "Bone Cancer","Osteosarcoma","Chondrosarcoma","Ewing Sarcoma","Rhabdomyosarcoma","Leiomyosarcoma","Liposarcoma","Synovial Sarcoma","Angiosarcoma","Kaposi Sarcoma","Fibrosarcoma","Desmoid Tumor",
  "Retinoblastoma","Uveal Melanoma","Eye (Ocular) Cancer","Merkel Cell Carcinoma","Basal Cell Carcinoma","Cutaneous Squamous Cell Carcinoma",
  "Nasopharyngeal Cancer","Oropharyngeal Cancer","Laryngeal Cancer","Hypopharyngeal Cancer","Salivary Gland Cancer","Nasal & Sinus Cancer",
  "Cholangiocarcinoma","Ampullary Cancer","Duodenal Cancer","Anal Cancer","Vaginal Cancer","Endometrial Cancer","Cancer of Unknown Primary (CUP)","Germ Cell Tumors", "Squamous Cell Carcinoma","Fallopian Tube Cancer","Primary Peritoneal Cancer",
  "Neuroblastoma","Wilms Tumor","Medulloblastoma","Hepatoblastoma","Langerhans Cell Histiocytosis",
  "Pheochromocytoma / Paraganglioma","Parathyroid Cancer","Pituitary Tumors","Adrenocortical Carcinoma",
  "Glioblastoma","Meningioma","Ependymoma","Craniopharyngioma","Pineal Tumors",
  "Hairy Cell Leukemia","Mycosis Fungoides / Cutaneous T-Cell Lymphoma","Histiocytosis",
  "Thymoma / Thymic Carcinoma",
  "Chordoma","Gestational Trophoblastic Disease (GTD)","Pseudomyxoma Peritonei",
];
export const TYPES = [
  TYPES_RAW[0],
  ...TYPES_RAW.slice(1).sort((a, b) => a.localeCompare(b)),
];
export const CURATED_VERIFIED_DATE = "2026-07-24";
export const CATS = {
  support: { label: "Support & community", color: "support" },
  financial: { label: "Financial help", color: "financial" },
  research: { label: "Research & advocacy", color: "research" },
  info: { label: "Information", color: "info" },
  practical: { label: "Lodging & travel", color: "practical" },
  caregiver: { label: "Caregivers", color: "caregiver" },
};

/* curated directory: [name, url, desc, [cats], [types]] -- "All" = serves any cancer */
export const ORGS = [
  ["American Cancer Society","https://www.cancer.org","Information, a 24/7 helpline, lodging (Hope Lodge), and rides to treatment.",["info","support","practical"],["All"]],
  ["CancerCare","https://www.cancercare.org","Free counseling, support groups, and limited financial assistance from oncology social workers.",["support","financial"],["All"]],
  ["Cancer Support Community","https://www.cancersupportcommunity.org","Support groups, a helpline, and education through local affiliates and online.",["support","info"],["All"]],
  ["National Cancer Institute","https://www.cancer.gov","Government source for plain-language information and a clinical trials database.",["info"],["All"]],
  ["Patient Advocate Foundation","https://www.patientadvocate.org","Case managers help with insurance and access; Co-Pay Relief assists with drug costs.",["financial","info"],["All"]],
  ["Family Reach","https://familyreach.org","Grants for everyday costs like rent, utilities, food, and transportation.",["financial"],["All"]],
  ["Triage Cancer","https://triagecancer.org","Free education and navigation on insurance, work, and finances.",["info","financial"],["All"]],
  ["Imerman Angels","https://imermanangels.com","One-on-one peer support, matching patients and caregivers with someone who's been there.",["support"],["All"]],
  ["Cancer Hope Network","https://www.cancerhopenetwork.org","Free, confidential one-on-one peer support from trained survivors.",["support"],["All"]],
  ["Stupid Cancer","https://stupidcancer.org","Community and resources for adolescents and young adults with cancer.",["support"],["All"]],
  ["Cancer and Careers","https://www.cancerandcareers.org","Help navigating work during and after treatment — rights, resumes, disclosure.",["info"],["All"]],
  ["Caregiver Action Network","https://www.caregiveraction.org","Education, peer support, and a help desk for family caregivers.",["caregiver"],["All"]],
  ["NeedyMeds","https://www.needymeds.org","A searchable directory of patient assistance and medication-cost programs.",["financial"],["All"]],
  ["HealthWell Foundation","https://www.healthwellfoundation.org","Disease-specific grants for copays and premiums when a fund is open.",["financial"],["All"]],
  ["PAN Foundation","https://www.panfoundation.org","Disease-specific funds for medication copays and premiums.",["financial"],["All"]],
  ["Good Days","https://www.mygooddays.org","Copay, travel, and premium assistance through disease-specific funds.",["financial"],["All"]],
  ["Lazarex Cancer Foundation","https://lazarex.org","Helps cover travel and out-of-pocket costs of joining a clinical trial.",["financial"],["All"]],
  ["Cancer Financial Assistance Coalition","https://www.cancerfac.org","A coalition that helps you find financial assistance by need and diagnosis.",["financial","info"],["All"]],
  ["Corporate Angel Network","https://www.corpangelnetwork.org","Arranges free travel to treatment on corporate aircraft.",["practical"],["All"]],
  ["Joe's House","https://www.joeshouse.org","A lodging directory for patients and families traveling for treatment.",["practical"],["All"]],
  ["Healthcare Hospitality Network","https://www.hhnetwork.org","Connects families to lodging near hospitals during treatment.",["practical"],["All"]],
  ["Ronald McDonald House Charities","https://www.rmhc.org","Lodging and support for families of children getting medical care.",["practical","support"],["All","Pediatric"]],
  ["National Brain Tumor Society","https://braintumor.org","Research funding, patient resources, and advocacy for brain tumors.",["research","support","info"],["Brain"]],
  ["American Brain Tumor Association","https://www.abta.org","Education, a care navigator line, and support for brain tumor patients.",["support","info","research"],["Brain"]],
  ["Musella Foundation","https://virtualtrials.org","Brain tumor information and a clinical trial finder, plus copay help.",["info","research","financial"],["Brain"]],
  ["GO2 for Lung Cancer","https://go2.org","Support line, navigation, and advocacy for lung cancer.",["support","info","research"],["Lung"]],
  ["LUNGevity Foundation","https://www.lungevity.org","Research, peer support, and patient education for lung cancer.",["research","support","info"],["Lung"]],
  ["Susan G. Komen","https://www.komen.org","Breast cancer research, a helpline, and some financial assistance.",["research","support","financial","info"],["Breast"]],
  ["Living Beyond Breast Cancer","https://www.lbbc.org","Programs, a helpline, and community for people with breast cancer.",["support","info"],["Breast"]],
  ["METAvivor","https://www.metavivor.org","Research and support focused on metastatic breast cancer.",["research","support"],["Breast"]],
  ["Young Survival Coalition","https://youngsurvival.org","Community and resources for young adults facing breast cancer.",["support","info"],["Breast"]],
  ["Colorectal Cancer Alliance","https://www.ccalliance.org","Helpline, financial assistance, and advocacy for colorectal cancer.",["support","financial","info"],["Colorectal"]],
  ["Fight Colorectal Cancer","https://fightcolorectalcancer.org","Research advocacy, resources, and a patient community.",["research","support","info"],["Colorectal"]],
  ["Prostate Cancer Foundation","https://www.pcf.org","The leading funder of prostate cancer research, with patient guides.",["research","info"],["Prostate"]],
  ["ZERO Prostate Cancer","https://zerocancer.org","Education, peer support, and financial assistance for prostate cancer.",["support","info","financial"],["Prostate"]],
  ["Leukemia & Lymphoma Society","https://www.lls.org","Research, copay and patient aid programs, and information specialists.",["research","support","financial","info"],["Blood (leukemia)","Lymphoma","Myeloma","Acute Myeloid Leukemia (AML)","Acute Lymphoblastic Leukemia (ALL)","Chronic Myeloid Leukemia (CML)","Chronic Lymphocytic Leukemia (CLL)","Hodgkin Lymphoma","Non-Hodgkin Lymphoma","Myelodysplastic Syndromes (MDS)","Myeloproliferative Neoplasms (MPN)","Plasma Cell Disorders"]],
  ["Lymphoma Research Foundation","https://lymphoma.org","Research funding, a helpline, and education for lymphoma.",["research","support","info"],["Lymphoma","Hodgkin Lymphoma","Non-Hodgkin Lymphoma","Follicular Lymphoma","Mantle Cell Lymphoma","Diffuse Large B-Cell Lymphoma (DLBCL)","Burkitt Lymphoma"]],
  ["International Myeloma Foundation","https://www.myeloma.org","Infoline, support, and research for multiple myeloma.",["research","support","info"],["Myeloma"]],
  ["Multiple Myeloma Research Foundation","https://themmrf.org","Drives myeloma research and offers patient resources.",["research","info"],["Myeloma"]],
  ["NMDP (Be The Match)","https://www.nmdp.org","Support and resources around blood stem cell and marrow transplant.",["info","practical","research"],["Blood (leukemia)","Lymphoma","Myeloma"]],
  ["National Ovarian Cancer Coalition","https://ovarian.org","Support programs and awareness for ovarian cancer.",["support","info"],["Ovarian / gynecologic","Fallopian Tube Cancer","Primary Peritoneal Cancer"]],
  ["Ovarian Cancer Research Alliance","https://ocrahope.org","Research funding and a patient helpline for ovarian cancer.",["research","support","info"],["Ovarian / gynecologic"]],
  ["Foundation for Women's Cancer","https://www.foundationforwomenscancer.org","Education and research across gynecologic cancers.",["info","research"],["Ovarian / gynecologic","Uterine","Vulvar","Vaginal Cancer","Endometrial Cancer","Gestational Trophoblastic Disease (GTD)"]],
  ["PanCAN","https://www.pancan.org","Patient services, clinical trial finder, and research for pancreatic cancer.",["research","support","info"],["Pancreatic"]],
  ["Lustgarten Foundation","https://lustgarten.org","The largest private funder of pancreatic cancer research.",["research","info"],["Pancreatic"]],
  ["Melanoma Research Foundation","https://melanoma.org","Research, support communities, and education for melanoma.",["research","support","info"],["Melanoma / skin","Uveal Melanoma"]],
  ["AIM at Melanoma","https://www.aimatmelanoma.org","Patient education, support, and a trial finder for melanoma.",["research","support","info"],["Melanoma / skin"]],
  ["Kidney Cancer Association","https://www.kidneycancer.org","Patient resources, a helpline, and research for kidney cancer.",["research","support","info"],["Kidney"]],
  ["Bladder Cancer Advocacy Network","https://bcan.org","Support, education, and research advocacy for bladder cancer.",["support","info","research"],["Bladder"]],
  ["Head and Neck Cancer Alliance","https://www.headandneck.org","Support and survivorship resources for head and neck cancers.",["support","info"],["Head & neck","Nasopharyngeal Cancer","Oropharyngeal Cancer","Laryngeal Cancer","Hypopharyngeal Cancer","Salivary Gland Cancer","Nasal & Sinus Cancer"]],
  ["SPOHNC","https://www.spohnc.org","Peer support for people with oral, head, and neck cancer.",["support"],["Head & neck","Nasopharyngeal Cancer","Oropharyngeal Cancer","Laryngeal Cancer","Hypopharyngeal Cancer","Salivary Gland Cancer","Nasal & Sinus Cancer"]],
  ["Sarcoma Foundation of America","https://www.curesarcoma.org","Research funding and patient resources for sarcoma.",["research","info"],["Sarcoma","Bone Cancer","Osteosarcoma","Chondrosarcoma","Ewing Sarcoma","Rhabdomyosarcoma","Leiomyosarcoma","Liposarcoma","Synovial Sarcoma","Angiosarcoma","Kaposi Sarcoma","Fibrosarcoma"]],
  ["Sarcoma Alliance","https://sarcomaalliance.org","Guidance, peer support, and a second-opinion fund for sarcoma.",["support","info","financial"],["Sarcoma","Bone Cancer","Osteosarcoma","Chondrosarcoma","Ewing Sarcoma","Rhabdomyosarcoma","Leiomyosarcoma","Liposarcoma","Synovial Sarcoma","Angiosarcoma","Kaposi Sarcoma","Fibrosarcoma"]],
  ["Blue Faery","https://bluefaery.org","Research and awareness focused on liver cancer.",["research","info"],["Liver"]],
  ["Debbie's Dream Foundation","https://debbiesdream.org","Support, education, and research for stomach (gastric) cancer.",["support","research","info"],["Gastric / esophageal"]],
  ["Esophageal Cancer Action Network","https://ecan.org","Awareness, education, and advocacy for esophageal cancer.",["info","research"],["Gastric / esophageal"]],
  ["Alex's Lemonade Stand Foundation","https://www.alexslemonade.org","Childhood cancer research funding and family travel/financial support.",["research","financial"],["Pediatric"]],
  ["St. Baldrick's Foundation","https://www.stbaldricks.org","A major funder of childhood cancer research.",["research"],["Pediatric"]],
  ["American Childhood Cancer Organization","https://www.acco.org","Resources and support for children with cancer and their families.",["support","info"],["Pediatric"]],
  ["ThyCa: Thyroid Cancer Survivors' Association","https://www.thyca.org","Peer support, education, and a helpline for thyroid cancer.",["support","info"],["Thyroid"]],
  ["Cervivor","https://cervivor.org","Survivor-led community, education, and advocacy for cervical cancer.",["support","info","research"],["Cervical"]],
  ["Testicular Cancer Society","https://www.testicularcancersociety.org","Education, peer support, and awareness for testicular cancer.",["support","info"],["Testicular","Germ Cell Tumors"]],
  ["Oral Cancer Foundation","https://oralcancerfoundation.org","Education, patient support, and screening awareness for oral cancer.",["info","support"],["Oral"]],
  ["Urology Care Foundation","https://www.urologyhealth.org","Patient education on penile and other urologic cancers.",["info"],["Penile"]],
  ["Cholangiocarcinoma Foundation","https://cholangiocarcinoma.org","Research, education, and support for bile duct cancer.",["research","support","info"],["Bile duct","Gallbladder","Cholangiocarcinoma","Ampullary Cancer","Duodenal Cancer"]],
  ["ACPMP Research Foundation","https://acpmp.org","Support and research for appendix cancer and related conditions.",["research","support"],["Appendix"]],
  ["Mesothelioma Applied Research Foundation","https://www.curemeso.org","Research funding and patient support for mesothelioma.",["research","support"],["Mesothelioma"]],
  ["Neuroendocrine Tumor Research Foundation","https://netrf.org","Research funding and patient resources for neuroendocrine tumors.",["research","info"],["Neuroendocrine tumor (NET)"]],
  ["The Life Raft Group","https://liferaftgroup.org","Research, education, and patient community for GIST.",["research","support","info"],["Gastrointestinal stromal tumor (GIST)"]],
  ["National Organization for Rare Disorders (NORD)","https://rarediseases.org","Information and a support network for rare diseases, including rare cancers.",["info","support"],["Adrenal","Small intestine","Other / rare","Cancer of Unknown Primary (CUP)","Eye (Ocular) Cancer","Retinoblastoma"]],
  ["International Waldenstrom's Macroglobulinemia Foundation","https://www.iwmf.com","Education, support, and research funding for Waldenström macroglobulinemia.",["support","info","research"],["Waldenström Macroglobulinemia"]],
  ["MDS Foundation","https://www.mds-foundation.org","Patient education and physician resources for myelodysplastic syndromes.",["info","research"],["Myelodysplastic Syndromes (MDS)"]],
  ["MPN Research Foundation","https://www.mpnresearchfoundation.org","Research funding and patient resources for myeloproliferative neoplasms.",["research","info"],["Myeloproliferative Neoplasms (MPN)","Essential Thrombocythemia","Polycythemia Vera","Primary Myelofibrosis"]],
  ["Desmoid Tumor Research Foundation","https://www.desmoidtumor.org","Research and patient support specifically for desmoid tumors.",["research","support"],["Desmoid Tumor"]],
  ["Skin Cancer Foundation","https://www.skincancer.org","Prevention education and patient information across skin cancer types.",["info"],["Melanoma / skin","Merkel Cell Carcinoma","Basal Cell Carcinoma","Cutaneous Squamous Cell Carcinoma","Squamous Cell Carcinoma"]],
["Anal Cancer Foundation","https://www.analcancerfoundation.org","Peer-to-peer support, financial resource lists, and education for anal cancer.",["support","info","financial"],["Anal Cancer"]],
  ["Children's Brain Tumor Foundation","https://cbtf.org","Research funding, education, and quality-of-life support for children with brain and spinal cord tumors.",["research","support","info"],["Brain","Glioblastoma","Meningioma","Ependymoma","Craniopharyngioma","Medulloblastoma","Pineal Tumors"]],
  ["Children's Neuroblastoma Cancer Foundation","https://www.cncfhope.org","Research funding and an annual education conference for families facing neuroblastoma.",["research","support","info"],["Neuroblastoma"]],
  ["Histiocytosis Association","https://histio.org","Education, peer support, and research funding for histiocytic disorders including LCH.",["support","research","info"],["Langerhans Cell Histiocytosis","Histiocytosis"]],
  ["Pheo Para Alliance","https://pheopara.org","Education, advocacy, and a global patient community for pheochromocytoma and paraganglioma.",["support","info","research"],["Pheochromocytoma / Paraganglioma"]],
  ["Pituitary Network Association","https://pituitary.org","Patient education, resource guides, and support groups for pituitary tumors and disorders.",["support","info"],["Pituitary Tumors"]],
  ["Adrenal Cure Collective","https://www.adrenalcurecollective.org","Nonprofit dedicated to funding research specifically for adrenocortical carcinoma.",["research","support"],["Adrenocortical Carcinoma"]],
  ["Hairy Cell Leukemia Foundation","https://www.hairycellleukemia.org","Patient education, expert referrals, and an online community for hairy cell leukemia.",["support","info","research"],["Hairy Cell Leukemia"]],
  ["Cutaneous Lymphoma Foundation","https://www.clfoundation.org","Education, treatment directories, and support for mycosis fungoides and cutaneous T-cell lymphoma.",["support","info"],["Mycosis Fungoides / Cutaneous T-Cell Lymphoma"]],
  ["Chordoma Foundation","https://www.chordomafoundation.org","Patient guidance, a doctor directory, and an online community for chordoma.",["support","info","research"],["Chordoma"]],
];